[package]
name = "cli-todo"
version = "0.1.0"
edition = "2021"
author = ["Ryana <https://github.com/Ryana-X-x>"]

description = "A simple cli todo app in rust that allows adding, removing and task listing"
license = "MIT"

[dependencies]


[[bin]]
name = "cli-todo"
path = "src/main.rs"
